CREATE TABLE pets
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo      VARCHAR(255)                            NOT NULL,
    nome      VARCHAR(255),
    raca      VARCHAR(255),
    idade     INT                                     NOT NULL,
    cor       VARCHAR(255),
    peso      FLOAT                                   NOT NULL,
    adotado   BOOLEAN,
    abrigo_id BIGINT,
    CONSTRAINT pk_pets PRIMARY KEY (id)
);

ALTER TABLE pets
    ADD CONSTRAINT FK_PETS_ON_ABRIGO FOREIGN KEY (abrigo_id) REFERENCES abrigos (id);
