CREATE TABLE tutores
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome     VARCHAR(255),
    telefone VARCHAR(255),
    email    VARCHAR(255),
    CONSTRAINT pk_tutores PRIMARY KEY (id)
);