CREATE TABLE adocoes
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data                 TIMESTAMP,
    tutor_id             BIGINT                                  NOT NULL,
    pet_id               BIGINT                                  NOT NULL,
    motivo               VARCHAR(255),
    status               VARCHAR(255),
    justificativa_status VARCHAR(255),
    CONSTRAINT pk_adocoes PRIMARY KEY (id)
);

ALTER TABLE adocoes
    ADD CONSTRAINT FK_ADOCOES_ON_PET FOREIGN KEY (pet_id) REFERENCES pets (id);

ALTER TABLE adocoes
    ADD CONSTRAINT FK_ADOCOES_ON_TUTOR FOREIGN KEY (tutor_id) REFERENCES tutores (id);